[package]
name = "strapdown-sim"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
strapdown-core = { path = "../core", features = ["clap"] }
log = "0.4"
env_logger = "0.11"
chrono = "0.4"

[[bin]]
name = "strapdown-sim"
path = "src/main.rs"
